server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: english_management_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/**
          filters:
            - StripPrefix=2
        - id: class_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/**
          filters:
            - StripPrefix=1
